### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kianenigma** [sacha-l/substrate-hacking#1]
Greetings -- I read most of your content and have some initial feedback on it. 

> A Council - made up of two groups (standard committee and technical committee)

This is a bit misleading. There is a module named collective, which can be instanciated. One instance is the council and the other one is TC. Thus, I would say: "A number of Collectives: From which Polkadot currently has 2, ..."

>  In a Substrate-based system of governance, including an Elections pallet implicitly specifies how the Treasury and Collective pallets interact. Election modules central to staking mechanims as well as voting on referenda. There are two Elections pallets in Substrate: one more simple (Elections) and one more sophisticated (Elections Phragmen).

ummm.. I am not sure about: 

- Elections pallet implicitly specifies how the Treasury and Collective pallets interact
  - My opinion: No -- election-phragmen does not mediate this. elections-phragmen only decides who are the members of the council.
- Election modules central to staking mechanims as well as voting on referenda
  - I think here you are confusing the election that happens in staking and the one that happens in elections-phragmen.

> LoserCandidate, BadReport and KickedMember are various handlers for different unbalanced reduction scenarios which each require Treasury

This is correct but I want to point out that is the only interaction that elections has with treasury: if someone gets slashed, then the money goes to treasury. It does _not_, however, dictate how treasury and council interact at all. 

> TODO: Difference between the two Elections pallets? Module import issues? Add examples of different configurations

The normal `elections` in deprecated and not maintained anymore. I would skip mentioning it at all if I were you.

--- 

All in all, great work and and enjoyed your description. But I think it can use a bit more accuracy. Unless, if you intentionally want it to be high level for non-technical users.

**Comment by sacha-l** [comment]
Greetings @kianenigma 👋🏻 ! Thanks for your comments and feedback, much appreciated. My objective with this is to gradually build accuracy by adding examples with code, showing how certain pallets can interact and be configured in different ways for an audience of developers looking to implement their own structures of governance. At the same time, I imagine it being a technical ressource that shines the flashlight for anyone to pick up on what's going on. 

I included all your points. The only hesitation I had was on how Elections-Phragmén can be used in different contexts. What I want to highlight is how although it's used for Council voting in Polkadot, it could very much be used in other scenarios. This is something I picked up on from [Bill's presentation](https://www.youtube.com/watch?v=9B10wX9Mphc). 

I hope the changes I made add accuracy and clarity. Thanks again.
